#!/usr/bin/env python3

import sys

from PyQt5.QtWidgets import QApplication

from inspectorwindow import InspectorWindow

app = QApplication(sys.argv)
window = InspectorWindow()
window.show()

sys.exit(app.exec_())
